version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=events-app
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_password@postgres:5432/events-app
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    depends_on:
      - postgres
    command: bash -c "npx prisma migrate dev --name init && npx prisma db seed && npm run dev"
